[project]
name = "pywebview-vue"
version = "0.1.0"
description = "escription"
readme = "README.md"
requires-python = ">=3.10.5"
dependencies = [
    "py2app>=0.28.8",
    "pyinstaller>=6.12.0",
    "pywebview>=5.4",
]
